-- NÃO APLICADO O PERCENTUAL - ORIGINAL - ( FOI ENTREGUE ESTA VERSÃO )
declare @ano varchar(4)
declare @ANO_FUT varchar(4)
declare @CONTROLE_ID int

set @ano = '2019'
set @ANO_FUT =  '2020'
set @CONTROLE_ID = 156;




WITH DADOS
AS (
SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
        (SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JANEIRO,
	    (SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) FEVEREIRO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) MARÇO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) ABRIL,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) MAIO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JUNHO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JULHO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) AGOSTO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) SETEMBRO,
		(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) OUTUBRO,
        (SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) NOVEMBRO,
        (SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) DEZEMBRO

FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '2' AND M.ECF_CONTROLE_ID = @CONTROLE_ID
WHERE M.ANO = @ANO
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

)
SELECT C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO, SUM(JANEIRO) AS JANEIRO, SUM(FEVEREIRO) AS FEVEREIRO, SUM(MARÇO) AS MARCO, SUM(ABRIL) AS ABRIL, SUM(MAIO) AS MAIO,
                                                        SUM(JUNHO) AS JUNHO, SUM(JULHO) AS JULHO, SUM(AGOSTO) AS AGOSTO, SUM(SETEMBRO) AS SETEMBRO, SUM(OUTUBRO) AS OUTUBRO,
														SUM(NOVEMBRO) AS NOVEMBRO, SUM(DEZEMBRO) AS DEZEMBRO

FROM DADOS C
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

UNION ALL

SELECT C.ORDEM,  C.CODIGO_LINHA, DESC_L210,C.SUBGRUPO, 
        SUM([006]) AS 'JANEIRO', 
		SUM([006]) + SUM([007]) AS 'FEVEREIRO', 
		SUM([006]) + SUM([007]) + SUM([008]) AS 'MARÇO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) AS 'ABRIL', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) AS 'MAIO',
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) AS 'JUNHO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011])  + SUM([012]) AS 'JULHO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011])  + SUM([012]) + SUM([001]) AS ' AGOSTO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011])  + SUM([012]) + SUM([001]) + SUM([002]) AS 'SETEMBRO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011])  + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) AS 'OUTUBRO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011])  + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) AS 'NOVEMBRO', 
		SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011])  + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) + SUM([005]) AS 'DEZEMBRO'

FROM (SELECT ACC_NUMBER, POSITION_PERIODO,  SUM(AMOUNT) VALOR              
      FROM ECF_MOV_KE5Z
	  WHERE PAIS = 'BR' AND ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
     GROUP BY ACC_NUMBER, POSITION_PERIODO ) SQ 
PIVOT (SUM(VALOR) FOR POSITION_PERIODO IN ([006], [007], [008], [009], [010], [011], [012], [001], [002], [003], [004], [005])) AS PT
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = ACC_NUMBER AND CODIGO_LINHA IN ('3') --,'34','35','29C','29B'
GROUP BY C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO
UNION ALL

SELECT ORDEM,  CODIGO_LINHA, DESC_L210, SUBGRUPO,

        CAST(SUM([6]) AS NUMERIC(18,2)) AS 'JANEIRO', 
		CAST(SUM([6]) + SUM([7]) AS NUMERIC(18,2)) AS 'FEVEREIRO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) AS NUMERIC(18,2))  AS 'MARÇO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) AS NUMERIC(18,2))  AS 'ABRIL', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) AS NUMERIC(18,2))  AS 'MAIO',
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11]) AS NUMERIC(18,2))  AS 'JUNHO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11])  + SUM([12]) AS NUMERIC(18,2))  AS 'JULHO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11])  + SUM([12]) + SUM([1]) AS NUMERIC(18,2))  AS ' AGOSTO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11])  + SUM([12]) + SUM([1]) + SUM([2]) AS NUMERIC(18,2))  AS 'SETEMBRO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11])  + SUM([12]) + SUM([1]) + SUM([2]) + SUM([3]) AS NUMERIC(18,2))  AS 'OUTUBRO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11])  + SUM([12]) + SUM([1]) + SUM([2]) + SUM([3]) + SUM([4]) AS NUMERIC(18,2))  AS 'NOVEMBRO', 
		CAST(SUM([6]) + SUM([7]) + SUM([8]) + SUM([9]) + SUM([10]) + SUM([11])  + SUM([12]) + SUM([1]) + SUM([2]) + SUM([3]) + SUM([4]) + SUM([5]) AS NUMERIC(18,2))  AS 'DEZEMBRO'
FROM (
SELECT C.ORDEM, DESC_L210, C.CODIGO_LINHA, F.MES_FISCAL,C.SUBGRUPO, X.ECF_CENTRO_CUSTO_ID 
	   ,CAST( COALESCE(SUM((F.VALOR/1) * (X.PERCENTUAL/100) ),0) AS NUMERIC(18,2)) AS VALOR
	  FROM ECF_FBL3N F
	  INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = F.NUMERO_CONTA
	  AND  C.CODIGO_LINHA IN ('9','11','15','16','18','23')   AND C.GRUPO = 6
	  INNER JOIN ECF_CENTRO_CUSTO CC ON CC.CENTRO_CUSTO = F.CENTRO_CUSTO 
      INNER JOIN (SELECT v.ECF_CENTRO_CUSTO_ID,  
		                    V.EXERCICIO,  
							V.DT_EXERCICIOFISCAL ,  
							CONVERT(INT,V.PERIODO_FISCAL) AS MES,  
							SUM(V.PERCENTUAL) as PERCENTUAL FROM ECF_VINCULO V
							INNER JOIN ECF_CENTRO_CUSTO C1 ON C1.ECF_CENTRO_CUSTO_ID = V.ECF_CENTRO_CUSTO_ID
							INNER JOIN ECF_CENTRO_CUSTO C2 ON C2.ECF_CENTRO_CUSTO_ID = V.ECF_CENTRO_CUSTO_FILHO 
							WHERE  SUBSTRING(C1.CENTRO_CUSTO,1,1) = SUBSTRING(C2.CENTRO_CUSTO,1,1)
							GROUP BY v.ECF_CENTRO_CUSTO_ID,   V.DT_EXERCICIOFISCAL , V.ECF_CENTRO_CUSTO_ID, V.PERIODO_FISCAL, V.EXERCICIO) 
							X ON X.ECF_CENTRO_CUSTO_ID = CC.ECF_CENTRO_CUSTO_ID
							AND X.DT_EXERCICIOFISCAL = @ANO
							AND X.EXERCICIO IN (@ANO, @ANO_FUT)
							AND X.MES = F.MES_FISCAL
   
          WHERE F.ano_base in (@ANO, @ANO_FUT) 
		  AND ECF_CONTROLE_ID = @CONTROLE_ID 
     GROUP BY C.ORDEM, C.CODIGO_LINHA, C.DESC_L210, F.MES_FISCAL, C.SUBGRUPO,  X.ECF_CENTRO_CUSTO_ID, X.PERCENTUAL) Q

PIVOT (SUM(VALOR) FOR MES_FISCAL IN ([6], [7], [8],[9], [10],[11],[12],[1], [2],[3],[4],[5])) AS PT
GROUP BY ORDEM,  CODIGO_LINHA, DESC_L210, SUBGRUPO

UNION ALL
SELECT C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO, 
                        SUM([006]) AS 'JANEIRO', 
			SUM([006]) + SUM([007]) AS 'FEVEREIRO', 
			SUM([006]) + SUM([007]) + SUM([008]) AS 'MARÇO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) AS 'ABRIL',    
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) AS 'MAIO', 
                        SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) AS 'JUNHO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) AS 'JULHO',     
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) AS 'AGOSTO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) AS 'SETEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) AS 'OUTUBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) AS 'NOVEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) + SUM([005]) AS 'DEZEMBRO'

FROM (SELECT ACC_NUMBER, POSITION_PERIODO,  SUM(AMOUNT) VALOR              
      FROM ECF_MOV_KE5Z
	  WHERE PAIS <> 'BR' AND ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
     GROUP BY ACC_NUMBER, POSITION_PERIODO ) SQ 
PIVOT (SUM(VALOR) FOR POSITION_PERIODO IN ([006], [007], [008], [009], [010], [011], [012], [001], [002], [003], [004], [005])) AS PT
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = ACC_NUMBER AND CODIGO_LINHA IN ('4') --,'34','35','29C','29B'
GROUP BY C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO
UNION ALL
SELECT C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,   
            SUM([006]) AS 'JANEIRO', 
			SUM([006]) + SUM([007]) AS 'FEVEREIRO', 
			SUM([006]) + SUM([007]) + SUM([008]) AS 'MARÇO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) AS 'ABRIL',    
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) AS 'MAIO', 
            SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) AS 'JUNHO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) AS 'JULHO',     
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) AS 'AGOSTO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) AS 'SETEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) AS 'OUTUBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) AS 'NOVEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) + SUM([005]) AS 'DEZEMBRO'
FROM (SELECT ACC_NUMBER, POSITION_PERIODO,  SUM(AMOUNT) VALOR              
      FROM ECF_MOV_KE5Z
      WHERE ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
     GROUP BY ACC_NUMBER, POSITION_PERIODO ) SQ 
PIVOT (SUM(VALOR) FOR POSITION_PERIODO IN ([006], [007], [008], [009], [010], [011], [012], [001], [002], [003], [004], [005])) AS PT
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = ACC_NUMBER AND CODIGO_LINHA IN ('29B') 
GROUP BY C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

UNION ALL

SELECT C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,    SUM(FEVEREIRO) - SUM(JANEIRO) AS JANEIRO, 
                                                           SUM(MARÇO)  - SUM(FEVEREIRO) AS FEVEREIRO, 
														   SUM(ABRIL) - SUM(MARÇO) AS MARCO,
														   SUM(MAIO)  - SUM(ABRIL) AS ABRIL ,
														   SUM(JUNHO) - SUM(MAIO) AS MAIO, 
														   SUM(JULHO)- SUM(JUNHO) AS JUNHO,
														   SUM(AGOSTO) - SUM(JULHO) AS JULHO,
														   SUM(SETEMBRO) - SUM(AGOSTO)  AS AGOSTO,
														   SUM(OUTUBRO) - SUM(SETEMBRO) AS SETEMBRO,
														   SUM(NOVEMBRO) - SUM(OUTUBRO) AS OUTUBRO,
														   SUM(DEZEMBRO)  - SUM(NOVEMBRO) AS NOVEMBRO,
														   SUM(DEZ_ANT) -  SUM(DEZEMBRO) AS DEZEMBRO
FROM (
				SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
				0 DEZ_ANT,
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JANEIRO,
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07)) FEVEREIRO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08)) MARÇO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)) ABRIL, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10)) MAIO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + SUM(M.VALOR_FIS_11)) JUNHO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + SUM(M.VALOR_FIS_11) + SUM(M.VALOR_FIS_12))  JULHO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
				SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + SUM(M.VALOR_FIS_11) + SUM(M.VALOR_FIS_12) + SUM(M.VALOR_FIS_13)) AGOSTO,         
		
				0 SETEMBRO, 
				0 OUTUBRO, 
				0 NOVEMBRO,
				0 DEZEMBRO        

				FROM ECF_MOV_F01 M
				INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '29C' AND C.NUMERO_CONTA   IN ('134032')
				WHERE M.ANO = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
				GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

				UNION ALL

				SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) DEZ_ANT,
				0 JANEIRO, 
				0 FEVEREIRO, 
				0 MARCO, 
				0 ABRIL, 
				0 MAIO, 
				0 JUNHO, 
				0 JULHO,
				0 AGOSTO,       
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02)) SETEMBRO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03)) OUTUBRO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04)) NOVEMBRO, 
				(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05)) DEZEMBRO
 				FROM ECF_MOV_F01 M
				INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '29C' AND C.NUMERO_CONTA  IN ('134032')
				WHERE M.ANO = @ANO_FUT AND ECF_CONTROLE_ID = @CONTROLE_ID
				GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO
      ) C
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO


UNION ALL

SELECT CC.ORDEM, CC.CODIGO_LINHA, CC.DESC_L210,CC.SUBGRUPO,   

            SUM([006]) AS 'JANEIRO', 
			SUM([006]) + SUM([007]) AS 'FEVEREIRO', 
			SUM([006]) + SUM([007]) + SUM([008]) AS 'MARÇO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) AS 'ABRIL',    
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) AS 'MAIO', 
            SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) AS 'JUNHO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) AS 'JULHO',     
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) AS 'AGOSTO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) AS 'SETEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) AS 'OUTUBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) AS 'NOVEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) + SUM([005]) AS 'DEZEMBRO'

FROM (
     SELECT X.ACC_NUMBER, X.POSITION_PERIODO, X.CENTRO_CUSTO,  SUM(X.AMOUNT) VALOR              
      FROM ECF_MOV_KE5Z X
      WHERE ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
	  AND EXISTS  (SELECT *
	                FROM [DBO].[ECF_CENTRO_CUSTO] A, [DBO].[ECF_CONTA]  B
                    WHERE  B.NUMERO_CONTA = X.ACC_NUMBER AND A.CENTRO_CUSTO = X.CENTRO_CUSTO AND  A.TP_CENTRO_CUSTO_ID = 2 AND B.CODIGO_LINHA = '29' )
     GROUP BY X.ACC_NUMBER, X.POSITION_PERIODO , X.CENTRO_CUSTO
     UNION 
	 -- PARTE ABAIXO FUNCIONA OK
     SELECT X.NUMERO_CONTA AS ACC_NUMBER, REPLICATE('0', 3 - LEN(X.MES_FISCAL)) + X.MES_FISCAL AS POSITION_PERIODO, X.CENTRO_CUSTO, SUM(X.VALOR) VALOR
     FROM ECF_FBL3N X
     WHERE X.ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
	 AND EXISTS  (SELECT * 
	                FROM [DBO].[ECF_CENTRO_CUSTO] A, [DBO].[ECF_CONTA]  B
                    WHERE  B.NUMERO_CONTA = X.NUMERO_CONTA AND A.CENTRO_CUSTO = X.CENTRO_CUSTO AND  A.TP_CENTRO_CUSTO_ID = 2 AND B.CODIGO_LINHA = '29' )

	 GROUP BY X.NUMERO_CONTA, X.MES_FISCAL, X.CENTRO_CUSTO

	 ) SQ 


PIVOT (SUM(VALOR) FOR POSITION_PERIODO IN ([006], [007], [008], [009], [010], [011], [012], [001], [002], [003], [004], [005])) AS PT
	 
	 INNER JOIN  (SELECT B.NUMERO_CONTA, A.CENTRO_CUSTO,  B.ORDEM, B.CODIGO_LINHA, B.DESC_L210, B.SUBGRUPO FROM [DBO].[ECF_CENTRO_CUSTO] A, [DBO].[ECF_CONTA]  B
       WHERE A.TP_CENTRO_CUSTO_ID = 2 AND B.CODIGO_LINHA = '29'
     
	    ) CC ON CC.NUMERO_CONTA = PT.ACC_NUMBER AND CC.CENTRO_CUSTO = PT.CENTRO_CUSTO
	 
	 
GROUP BY CC.ORDEM, CC.CODIGO_LINHA, CC.DESC_L210,CC.SUBGRUPO


UNION ALL


SELECT ORDEM,  CODIGO_LINHA, DESC_L210,SUBGRUPO, SUM(JANEIRO) AS JANEIRO, SUM(FEVEREIRO) AS FEVEREIRO, SUM(MARCO) AS MARCO, SUM(ABRIL) AS ABRIL, 
SUM(MAIO) AS MAIO, SUM(JUNHO) AS JUNHO, SUM(JULHO) AS JULHO, SUM(AGOSTO) AS AGOSTO,
SUM(SETEMBRO) AS SETEMBRO, SUM(OUTUBRO) AS OUTUBRO, SUM(NOVEMBRO) AS NOVEMBRO, SUM(DEZEMBRO) AS DEZEMBRO
FROM
(


SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,

		-1* (SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + SUM(M.VALOR_FIS_07))  JANEIRO, 

		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08)) FEVEREIRO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09) ) MARCO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09) +  SUM(M.VALOR_FIS_10) ) ABRIL, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + + SUM(M.VALOR_FIS_11)) MAIO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + SUM(M.VALOR_FIS_11) + SUM(M.VALOR_FIS_12) )  JUNHO, 
		
		0 JULHO,         
		
		0 AGOSTO, 
		
		0 SETEMBRO, 
		
		0 OUTUBRO, 
        
		0 NOVEMBRO, 
		
		0 DEZEMBRO         

FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '30'
 AND C.NUMERO_CONTA  IN ('131000','132000','133000','134000','134032','138000','138100')
WHERE M.ANO = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

UNION ALL

SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
		0 JANEIRO, 
		0 FEVEREIRO, 
		0 MARCO, 	
		0 ABRIL, 	
		0 MAIO, 	
		0 JUNHO, 
		-1*(SUM(M.VALOR_FIS_01)  ) JULHO, 
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02)  ) AGOSTO, 
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) ) SETEMBRO,         
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04)) OUTUBRO, 		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) ) NOVEMBRO,        
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05)  +  SUM(M.VALOR_FIS_06)) DEZEMBRO
FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '30'
 AND C.NUMERO_CONTA  IN ('131000','132000','133000','134000','134032','138000','138100')
WHERE M.ANO = @ANO_FUT AND ECF_CONTROLE_ID = @CONTROLE_ID
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO
) X

GROUP BY ORDEM,  CODIGO_LINHA, DESC_L210,SUBGRUPO

UNION ALL

SELECT X.ORDEM, X.CODIGO_LINHA, X.DESC_L210,X.SUBGRUPO, SUM(JANEIRO) AS JANEIRO, SUM(FEVEREIRO) AS FEVEREIRO, SUM(MARÇO) AS MARCO, SUM(ABRIL) AS ABRIL, SUM(MAIO) AS MAIO,
                                                        SUM(JUNHO) AS JUNHO, SUM(JULHO) AS JULHO, SUM(AGOSTO) AS AGOSTO, SUM(SETEMBRO) AS SETEMBRO, SUM(OUTUBRO) AS OUTUBRO,
														SUM(NOVEMBRO) AS NOVEMBRO, SUM(DEZEMBRO) AS DEZEMBRO
FROM (
				SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JANEIRO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) FEVEREIRO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) MARÇO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) ABRIL,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) MAIO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JUNHO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) JULHO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) AGOSTO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) SETEMBRO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) OUTUBRO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) NOVEMBRO,
						(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06)) DEZEMBRO

				FROM ECF_MOV_F01 M
				INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '33' AND  C.NUMERO_CONTA  = '134001'
				WHERE M.ANO = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
				GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

) X
GROUP BY  X.ORDEM, X.CODIGO_LINHA, X.DESC_L210, X.SUBGRUPO

UNION ALL

SELECT ORDEM, C.CODIGO_LINHA, C.DESC_L210, C.SUBGRUPO, 
            SUM([006]) AS 'JANEIRO', 
			SUM([006]) + SUM([007]) AS 'FEVEREIRO', 
			SUM([006]) + SUM([007]) + SUM([008]) AS 'MARÇO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) AS 'ABRIL',    
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) AS 'MAIO', 
            SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) AS 'JUNHO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) AS 'JULHO',     
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) AS 'AGOSTO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) AS 'SETEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) AS 'OUTUBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) AS 'NOVEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) + SUM([005]) AS 'DEZEMBRO'

FROM (SELECT ACC_NUMBER, POSITION_PERIODO,  SUM(AMOUNT) VALOR              
      FROM ECF_MOV_KE5Z 
	  WHERE PAIS = 'BR' AND PURCHASING_DOC <> '' AND ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
     GROUP BY ACC_NUMBER, POSITION_PERIODO ) SQ 
PIVOT (SUM(VALOR) FOR POSITION_PERIODO IN ([006], [007], [008], [009], [010], [011], [012], [001], [002], [003], [004], [005])) AS PT
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = ACC_NUMBER AND CODIGO_LINHA IN ('34') 
GROUP BY C.ORDEM, C.CODIGO_LINHA,  C.DESC_L210,C.SUBGRUPO
UNION ALL
SELECT C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,  

            SUM([006]) AS 'JANEIRO', 
			SUM([006]) + SUM([007]) AS 'FEVEREIRO', 
			SUM([006]) + SUM([007]) + SUM([008]) AS 'MARÇO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) AS 'ABRIL',    
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) AS 'MAIO', 
            SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) AS 'JUNHO',   
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) AS 'JULHO',     
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) AS 'AGOSTO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) AS 'SETEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) AS 'OUTUBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) AS 'NOVEMBRO', 
			SUM([006]) + SUM([007]) + SUM([008]) + SUM([009]) + SUM([010]) + SUM([011]) + SUM([012]) + SUM([001]) + SUM([002]) + SUM([003]) + SUM([004]) + SUM([005]) AS 'DEZEMBRO'

FROM (SELECT ACC_NUMBER, POSITION_PERIODO,  SUM(AMOUNT) VALOR              
      FROM ECF_MOV_KE5Z
	  WHERE PAIS <> 'BR' AND PURCHASING_DOC <> '' AND ANO_BASE = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
     GROUP BY ACC_NUMBER, POSITION_PERIODO ) SQ 
PIVOT (SUM(VALOR) FOR POSITION_PERIODO IN ([006], [007], [008], [009], [010], [011], [012], [001], [002], [003], [004], [005])) AS PT
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = ACC_NUMBER AND CODIGO_LINHA IN ('35')
GROUP BY C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO
UNION ALL
SELECT ORDEM,  CODIGO_LINHA, DESC_L210,SUBGRUPO, 

 SUM(JANEIRO) AS JANEIRO, SUM(FEVEREIRO) AS FEVEREIRO, SUM(MARCO) AS MARCO, SUM(ABRIL) AS ABRIL, 
SUM(MAIO) AS MAIO, SUM(JUNHO) AS JUNHO, SUM(JULHO) AS JULHO, SUM(AGOSTO) AS AGOSTO,
SUM(SETEMBRO) AS SETEMBRO, SUM(OUTUBRO) AS OUTUBRO, SUM(NOVEMBRO) AS NOVEMBRO, SUM(DEZEMBRO) AS DEZEMBRO


FROM
(


SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,

		-1* (SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + SUM(M.VALOR_FIS_07))  JANEIRO, 

		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08)) FEVEREIRO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)) MARCO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09) +  SUM(M.VALOR_FIS_10) ) ABRIL, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + + SUM(M.VALOR_FIS_11)) MAIO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) + SUM(M.VALOR_FIS_06) + 
		SUM(M.VALOR_FIS_07) + SUM(M.VALOR_FIS_08) + SUM(M.VALOR_FIS_09)  + SUM(M.VALOR_FIS_10) + SUM(M.VALOR_FIS_11) + SUM(M.VALOR_FIS_12) )  JUNHO, 
		
		0 JULHO,         
		
		0 AGOSTO, 
		
		0 SETEMBRO, 
		
		0 OUTUBRO, 
        
		0 NOVEMBRO, 
		
		0 DEZEMBRO         

FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '36' AND C.NUMERO_CONTA  = '134001'
WHERE M.ANO = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

UNION ALL

SELECT C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,

		0 JANEIRO, 

		0 FEVEREIRO, 
		
		0 MARCO, 
		
		0 ABRIL, 
		
		0 MAIO, 
		
		0 JUNHO, 

		-1*(SUM(M.VALOR_FIS_01)  ) JULHO, 

		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02)  ) AGOSTO, 

		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) ) SETEMBRO, 

        
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04)) OUTUBRO, 
		
		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05) ) NOVEMBRO,        

		-1*(SUM(M.VALOR_FIS_01)  + SUM(M.VALOR_FIS_02) + SUM(M.VALOR_FIS_03) + SUM(M.VALOR_FIS_04) + SUM(M.VALOR_FIS_05)  +  SUM(M.VALOR_FIS_06)) DEZEMBRO




FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '36' AND C.NUMERO_CONTA  = '134001'
WHERE M.ANO = @ANO_FUT AND ECF_CONTROLE_ID = @CONTROLE_ID
GROUP BY  C.ORDEM, C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO


) X

GROUP BY ORDEM,  CODIGO_LINHA, DESC_L210,SUBGRUPO


UNION ALL


SELECT Y.ORDEM, Y.CODIGO_LINHA, Y.DESC_L210, Y.SUBGRUPO, 
SUM(JANEIRO) AS JANEIRO, 
SUM(JANEIRO) + SUM(FEVEREIRO) AS FEVEREIRO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) AS MARCO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) AS ABRIL, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) AS MAIO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) AS JUNHO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) + SUM(JULHO) AS JULHO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) + SUM(JULHO) + SUM(AGOSTO) AS AGOSTO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) + SUM(JULHO) + SUM(AGOSTO) + SUM(SETEMBRO) AS SETEMBRO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) + SUM(JULHO) + SUM(AGOSTO) + SUM(SETEMBRO) + SUM(OUTUBRO) AS OUTUBRO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) + SUM(JULHO) + SUM(AGOSTO) + SUM(SETEMBRO) + SUM(OUTUBRO) + SUM(NOVEMBRO) AS NOVEMBRO, 
SUM(JANEIRO) + SUM(FEVEREIRO) + SUM(MARCO) + SUM(ABRIL) + SUM(MAIO) + SUM(JUNHO) + SUM(JULHO) + SUM(AGOSTO) + SUM(SETEMBRO) + SUM(OUTUBRO) + SUM(NOVEMBRO) + SUM(DEZEMBRO) AS DEZEMBRO


FROM (
SELECT  C.ORDEM,  '997' AS CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
SUM(M.VALOR_FIS_06) AS JANEIRO,
SUM(M.VALOR_FIS_07) AS FEVEREIRO, 
SUM(M.VALOR_FIS_08) AS MARCO, 
SUM(M.VALOR_FIS_09) AS ABRIL, 
SUM(M.VALOR_FIS_10) AS MAIO, 
SUM(M.VALOR_FIS_11) AS JUNHO, 
SUM(M.VALOR_FIS_12) AS JULHO,
0 AS AGOSTO , 
0 AS SETEMBRO, 
0 AS OUTUBRO, 
0 AS NOVEMBRO, 
0AS DEZEMBRO

FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '29A'
WHERE M.ANO = @ANO AND ECF_CONTROLE_ID = @CONTROLE_ID
GROUP BY C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO

UNION ALL

SELECT  C.ORDEM,  '997' AS CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO,
0 AS JANEIRO,
0 AS FEVEREIRO, 
0 AS MARCO, 
0 AS ABRIL, 
0 AS MAIO, 
0 AS JUNHO, 
0 AS JULHO,
SUM(M.VALOR_FIS_01) AS AGOSTO , 
SUM(M.VALOR_FIS_02) AS SETEMBRO, 
SUM(M.VALOR_FIS_03) AS OUTUBRO, 
SUM(M.VALOR_FIS_04) AS NOVEMBRO, 
SUM(M.VALOR_FIS_05) AS DEZEMBRO

FROM ECF_MOV_F01 M
INNER JOIN ECF_CONTA C ON C.NUMERO_CONTA = M.NUMERO_CONTA AND C.CODIGO_LINHA = '29A'
WHERE M.ANO = @ANO_FUT AND ECF_CONTROLE_ID = @CONTROLE_ID
GROUP BY C.ORDEM,  C.CODIGO_LINHA, C.DESC_L210,C.SUBGRUPO
) Y
GROUP BY Y.ORDEM, Y.CODIGO_LINHA, Y.DESC_L210, Y.SUBGRUPO
ORDER BY C.SUBGRUPO, C.ORDEM
